name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install modules
        run: yarn
        working-directory: client
      - name: Build
        run: yarn build
        working-directory: client
      - name: Run unit tests
        run: yarn test
        working-directory: client
      - name: Install modules
        run: yarn
        working-directory: server
      - name: Build
        run: yarn build
        working-directory: server
      - name: Run unit tests
        run: yarn test
        working-directory: client